from typing import Any, Dict

from backend.agents.nodes import AgentDecision
from backend.agents.graph import run_agent


def _make_mock_llm(decision_obj: AgentDecision):
    def mock_provider(system_prompt: str, user_prompt: str) -> AgentDecision:
        return decision_obj
    return mock_provider


class TestAgentGraphDirect:
    def test_vpn_query_resolve_with_kb02(self):
        mock = AgentDecision(
            decision="RESOLVE",
            intent="VPN credentials expired",
            response=(
                "Per KB-02 (VPN Access), VPN credentials expire every 90 days and must "
                "be renewed. Please visit the password/VPN renewal portal to regenerate "
                "credentials. No credentials have been modified by this system."
            ),
            clarification_question=None,
            escalation_reason=None,
            source_policy_ids=["KB-02"],
        )
        result = run_agent(
            user_query="My VPN stopped working. It says my credentials expired.",
            llm_provider=_make_mock_llm(mock),
        )
        assert result.get("decision") == "RESOLVE"
        assert "KB-02" in result.get("source_policy_ids", [])
        assert result.get("response") is not None
        assert result.get("clarification_question") is None
        assert result.get("escalation_reason") is None

    def test_guest_wifi_query_resolve_with_kb07(self):
        mock = AgentDecision(
            decision="RESOLVE",
            intent="Guest Wi-Fi for visitor",
            response=(
                "Per KB-07 (Guest Wi-Fi Access), guest Wi-Fi credentials can be "
                "generated by any employee at the front-desk kiosk. No IT ticket is "
                "required."
            ),
            clarification_question=None,
            escalation_reason=None,
            source_policy_ids=["KB-07"],
        )
        result = run_agent(
            user_query="I need guest Wi-Fi for someone visiting tomorrow.",
            llm_provider=_make_mock_llm(mock),
        )
        assert result.get("decision") == "RESOLVE"
        assert "KB-07" in result.get("source_policy_ids", [])
        assert result.get("response") is not None

    def test_phishing_query_escalate_with_kb09(self):
        mock = AgentDecision(
            decision="ESCALATE",
            intent="Suspected phishing email",
            response=(
                "Suspected phishing must be reported immediately. Your request has "
                "been escalated to the Security team per policy."
            ),
            clarification_question=None,
            escalation_reason=(
                "KB-09 requires suspected phishing and security incidents to be "
                "handled by the Security/SOC team directly."
            ),
            source_policy_ids=["KB-09"],
        )
        result = run_agent(
            user_query="I received a phishing email asking for my login.",
            llm_provider=_make_mock_llm(mock),
        )
        assert result.get("decision") == "ESCALATE"
        assert "KB-09" in result.get("source_policy_ids", [])
        assert result.get("escalation_reason") is not None
        assert result.get("clarification_question") is None

    def test_vague_request_asks_clarification(self):
        mock = AgentDecision(
            decision="ASK_CLARIFICATION",
            intent="Unspecified IT issue",
            response=None,
            clarification_question=(
                "What isn't working — your laptop, VPN, email, printer, "
                "or another IT service?"
            ),
            escalation_reason=None,
            source_policy_ids=[],
        )
        result = run_agent(
            user_query="Hey, it's not working.",
            llm_provider=_make_mock_llm(mock),
        )
        assert result.get("decision") == "ASK_CLARIFICATION"
        q = result.get("clarification_question")
        assert q is not None and isinstance(q, str) and len(q.strip()) > 0
        assert result.get("response") is None
        assert result.get("escalation_reason") is None

    def test_no_policy_unrelated_query_handled_safely(self):
        mock = AgentDecision(
            decision="ASK_CLARIFICATION",
            intent="Unknown request outside policy scope",
            response=None,
            clarification_question=(
                "I didn't find an IT policy matching your request. Could you "
                "describe which IT service or equipment this relates to?"
            ),
            escalation_reason=None,
            source_policy_ids=[],
        )
        result = run_agent(
            user_query="What is the weather today?",
            llm_provider=_make_mock_llm(mock),
        )
        decision = result.get("decision")
        assert decision in {"ASK_CLARIFICATION", "ESCALATE"}
        assert result.get("source_policy_ids") == []


class TestAgentEndpoint:
    def test_endpoint_returns_expected_structure(self):
        from fastapi.testclient import TestClient
        from backend.main import app

        client = TestClient(app)

        def _stub(system_prompt: str, user_prompt: str) -> AgentDecision:
            return AgentDecision(
                decision="RESOLVE",
                intent="VPN credentials expired",
                response="KB-02 says VPN credentials expire every 90 days. Renew online.",
                clarification_question=None,
                escalation_reason=None,
                source_policy_ids=["KB-02"],
            )

        import backend.agents.nodes as nodes_mod

        orig_default = nodes_mod.default_llm_provider
        try:
            nodes_mod.default_llm_provider = _stub
            resp = client.post(
                "/agent/chat",
                json={"message": "My VPN stopped working."},
            )
        finally:
            nodes_mod.default_llm_provider = orig_default

        assert resp.status_code == 200, f"status={resp.status_code} body={resp.text}"
        data: Dict[str, Any] = resp.json()
        assert "decision" in data
        assert data["decision"] == "RESOLVE"
        assert "intent" in data
        assert "response" in data
        assert "clarification_question" in data
        assert "escalation_reason" in data
        assert "source_policy_ids" in data
        assert "KB-02" in data.get("source_policy_ids", [])

    def test_endpoint_empty_message(self):
        from fastapi.testclient import TestClient
        from backend.main import app

        client = TestClient(app)
        resp = client.post("/agent/chat", json={"message": ""})
        assert resp.status_code == 200
        data = resp.json()
        assert data.get("decision") == "ASK_CLARIFICATION"
        assert data.get("error") is not None
